sonar.projectKey=goruum_ruum
sonar.organization=goruum

sonar.projectName=Ruum
sonar.projectVersion=1.0

# Source code
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/examples/**,**/testdata/**

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

# Coverage
sonar.go.coverage.reportPaths=coverage.out

# Language
sonar.language=go
sonar.sourceEncoding=UTF-8

# SCM
sonar.scm.provider=git

# Links
sonar.links.homepage=https://github.com/goruum/ruum
sonar.links.ci=https://github.com/goruum/ruum/actions
sonar.links.scm=https://github.com/goruum/ruum
sonar.links.issue=https://github.com/goruum/ruum/issues

